### PR TITLE
Ab#5365 kibble award categories

### PR DESCRIPTION
**Pull request by matthewthomsonnz**
- adds award categories to kibble
- requires [this branch of meta](https://github.com/indiereign/shift72-meta/pull/285) to work

### CODE REVIEW

**Comment by sarge** [comment]
Are award categories only for films?

**Comment by matthewthomsonnz** [comment]
> Are award categories only for films?

Yeah at this stage - [gdoc](https://docs.google.com/document/d/1YXl0uJgYKDKVVfKJ3v8-jPjBi66AkkB-Qh5TiZYeIAw/edit#heading=h.w3jg0f6sfg5c)

**Comment by stajs** [comment]
I want to question the pragmatism - our clean cut lines don't always align with the mess of real world usage. We have a number of clients abusing TV shows for films, I'm not always sure why but I assume some prefer it over bundles. As an example, [Film at Lincoln](https://virtual.filmlinc.org/admin/#/tv?page=1) has a mix of usages with ["Her Name Was Europa, preceded by A Night At The Opera"](https://virtual.filmlinc.org/admin/#/tv/1318/season/1/episodes) being an interesting format they've settled on by having episodes for Intro/Short/Feature/Q&A.

image

We could say "how sad, too bad" but it would be nice if the "film" could partake in awards.

**Comment by matthewthomsonnz** [comment]
> I want to question the pragmatism - our clean cut lines don't always align with the mess of real world usage. We have a number of clients abusing TV shows for films, I'm not always sure why but I assume some prefer it over bundles. As an example, [Film at Lincoln](https://virtual.filmlinc.org/admin/#/tv?page=1) has a mix of usages with ["Her Name Was Europa, preceded by A Night At The Opera"](https://virtual.filmlinc.org/admin/#/tv/1318/season/1/episodes) being an interesting format they've settled on by having episodes for Intro/Short/Feature/Q&A.
> 
> 
> We could say "how sad, too bad" but it would be nice if the "film" could partake in awards.

> @stajs @matthewthomsonnz I would assume that they are wanting a playlist in this instance

Thanks playlist sounds good. I imagine you could just hopefully change the media_contents tv_id/season/episode for new film_ids and it would be good to go.

**Comment by sarge** [comment]
@matthewthomsonnz @stajs At the risk of delaying this feature for everyone, I think we should release this for Films. Film At Lincoln can review their approach if they like and use bonus content as the gods intended. I will follow up with Nev regarding the priority of voting for tv seasons

**Comment by additiverich** [comment]
Seems like the decision is to ship for Films and add tv support later?

**Pull request merged**
