### PR TITLE
Pass goreleaser OS to deploy script

### LINKED ISSUE #114: `make release` throws error when copying to aws
As per .goreleaser.yml, for each target `post: sh ./deploy_aws.sh {{.Version}} {{.Os}}` is executed but on my machine (OS X) the template `.Os` doesn't match a key entry

```
⨯ release failed after 9.71s error=post hook failed: template: tmpl:1:34: executing "tmpl" at <.Os>: map has no entry for key "Os"
```

I've hard-coded this to 'linux' for now but it deploys 3x at the moment

### PR DESCRIPTION
**Pull request by stajs**
Closes #114. Fixes [AB#7838](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/7838).

### CODE REVIEW

**Comment by stajs** [comment]
@additiverich as discussed in #114, we don't seem to be able to replicate the issue so reverting the change.

**Review by curtisadams28 — APPROVED** [review]

**Review by brynyShift72 — APPROVED** [review]

**Comment by PeculiarGoat** [comment]
@stajs I've tried testing on the linux machine this with that script in the linked issue [#114](https://github.com/shift72/kibble/issues/114) but I keep getting an error:
`release failed after 0.07s error=found 2 builds with the ID 'shift72-kibble', please fix your config`

The only thing that has changed in the config is the release and blobs blocks are commented out as described in issue #144.  Not sure what the problem is!

**Review by l0ud0gg — APPROVED** [review]

**Review by smitsanghvi21 — APPROVED** [review]

**Comment by stajs** [comment]
@PeculiarGoat Do you still have your Linux machine or have you given it back? The error you found seems to be a messed up config with [two builds using a default ID](https://github.com/goreleaser/goreleaser/issues/1090) - suggest it was a copypasta mistake. [This is the branch](https://github.com/shift72/kibble/compare/goreleaser-os) if you wanted to confirm. I just tried that branch with the latest goreleaser 1.9.1 and got the expected results.

**Comment by stajs** [comment]
@PeculiarGoat If you aren't motivated to confirm, can you delete that branch for me? Just leaving it hanging around for you now.

**Comment by PeculiarGoat** [comment]
I'll just delete that branch then since this is already merged!

**Pull request merged**
